---
name: Hyper-Developer
version: 0.07
author:
  - 'Andreas Specht <acid@cpan.org>'
abstract: Hyper Developer Tools
license: artistic
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  Class::Std: 0
  Class::Std::Storable: 0
  Config::IniFiles: 0
  Cwd: 0
  Data::Dumper: 0
  English: 0
  File::Basename: 0
  File::Find: 0
  File::Path: 0
  File::Spec: 0
  Getopt::Long: 0
  Graph::Easy: 0
  Graph::Easy::As_svg: 0
  HTTP::Server::Simple::CGI: 0
  HTTP::Server::Simple::Static: 0
  Hyper: v0.03
  Hyper::Config::Reader::Container: 0
  Hyper::Config::Reader::Flow: 0
  Hyper::Control::Container: 0
  Hyper::Control::Flow: 0
  Hyper::Error: 0
  Hyper::Functions: 0
  Hyper::Singleton::Context: 0
  IO::Scalar: 0
  Module::Refresh: 0
  Parse::RecDescent: 0
  Pod::Usage: 0
  Template: 0
  Time::HiRes: 0
  version: 0
build_requires:
  IO::Scalar: 0
  Test::Class: 0
  Test::Exception: 0
  Test::More: 0
  Test::Pod: 1
  Test::Pod::Coverage: 1
  Test::Prereq::Build: 0
provides:
  Hyper::Developer:
    file: lib/Hyper/Developer.pm
    version: v0.07
  Hyper::Developer::Generator:
    file: lib/Hyper/Developer/Generator.pm
    version: v0.01
  Hyper::Developer::Generator::Control:
    file: lib/Hyper/Developer/Generator/Control.pm
    version: v0.01
  Hyper::Developer::Generator::Control::Container:
    file: lib/Hyper/Developer/Generator/Control/Container.pm
    version: v0.01
  Hyper::Developer::Generator::Control::ContainerFlow:
    file: lib/Hyper/Developer/Generator/Control/ContainerFlow.pm
    version: v0.01
  Hyper::Developer::Generator::Control::Flow:
    file: lib/Hyper/Developer/Generator/Control/Flow.pm
    version: v0.01
  Hyper::Developer::Generator::Environment:
    file: lib/Hyper/Developer/Generator/Environment.pm
    version: v0.01
  Hyper::Developer::Model::Viewer:
    file: lib/Hyper/Developer/Model/Viewer.pm
    version: v0.1
  Hyper::Developer::Server:
    file: lib/Hyper/Developer/Server.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
no_index:
  namespace: Hyper::Developer::var
